// <auto-generated />
using System;
using MINI_AGENDA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MINI_AGENDA.Migrations
{
    [DbContext(typeof(MiniAgendaDbContext))]
    partial class MiniAgendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MINI_AGENDA.Models.Cita.Cita", b =>
                {
                    b.Property<int>("idCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCita"));

                    b.Property<string>("estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("fechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<TimeSpan>("horaCita")
                        .HasColumnType("time");

                    b.Property<int>("idmedico")
                        .HasColumnType("int");

                    b.Property<int>("idpaciente")
                        .HasColumnType("int");

                    b.Property<string>("motivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("motivoCancelacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idCita");

                    b.HasIndex("idpaciente");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Medico.Especialidad", b =>
                {
                    b.Property<int>("idEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEspecialidad"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("DuracionCita")
                        .HasColumnType("smallint");

                    b.Property<bool>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("idEspecialidad");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Medico.HorarioAtencion", b =>
                {
                    b.Property<int>("idHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idHorario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("diasemana")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan>("horafin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("horainicio")
                        .HasColumnType("time");

                    b.Property<int>("idMedico")
                        .HasColumnType("int");

                    b.HasKey("idHorario");

                    b.HasIndex("idMedico");

                    b.ToTable("HorarioAtencion", t =>
                        {
                            t.HasCheckConstraint("CHK_Dia_Semana", "DiaSemana BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CHK_Horario_Valido", "HoraFin > HoraInicio");
                        });
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Medico.MMedico", b =>
                {
                    b.Property<int>("idMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMedico"));

                    b.Property<bool>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idMedico");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Medico.MedicoEspecialidad", b =>
                {
                    b.Property<int>("idMedico")
                        .HasColumnType("int");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("int");

                    b.HasKey("idMedico", "idEspecialidad");

                    b.HasIndex("idEspecialidad");

                    b.ToTable("MedicoEspecialidad");
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Pacientes.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPaciente"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("idPaciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Cita.Cita", b =>
                {
                    b.HasOne("MINI_AGENDA.Models.Medico.MMedico", null)
                        .WithMany()
                        .HasForeignKey("idpaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MINI_AGENDA.Models.Pacientes.Paciente", null)
                        .WithMany()
                        .HasForeignKey("idpaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Medico.HorarioAtencion", b =>
                {
                    b.HasOne("MINI_AGENDA.Models.Medico.MMedico", null)
                        .WithMany()
                        .HasForeignKey("idMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MINI_AGENDA.Models.Medico.MedicoEspecialidad", b =>
                {
                    b.HasOne("MINI_AGENDA.Models.Medico.Especialidad", null)
                        .WithMany()
                        .HasForeignKey("idEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MINI_AGENDA.Models.Medico.MMedico", null)
                        .WithMany()
                        .HasForeignKey("idMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
