version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_miniagenda
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Pass123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: ./MINI-AGENDA
      dockerfile: Dockerfile
    container_name: api_miniagenda
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiniAgenda;User=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;

  db_init:
    image: mcr.microsoft.com/mssql-tools
    container_name: db_init_miniagenda
    depends_on:
      - sqlserver
    volumes:
      - ./Database:/scripts
    entrypoint: >
      /bin/bash -c "
      echo 'Esperando SQL Server...';
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong!Pass123 -i /scripts/init.sql;
      echo 'Base de datos creada'; "

volumes:
  sql_data: